CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY ,
    username VARCHAR(255) NOT NULL ,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    CHECK ( role IN ('USER','ADMIN'))
);